configure_dotfiles: true
configure_sudoers: false
configure_terminal: false
configure_osx: false
configure_dock: true

dockitems_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - "System Preferences"
  - Calendar
  - TV
  - Podcasts
  - Music
  - News

dockitems_persist:
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 1
  - name: Bitwarden
    path: "/Applications/Bitwarden.app"
    pos: 2

dotfiles_repo: git@github.com:enlewof/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/code/dotfiles
dotfiles_files:
  - .aliases
  - .p10k.zsh
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  - antigen
  - pre-commit
  - wget

homebrew_cask_apps:
  - bitwarden
  - brave-browser
  - iterm2
  - spotify
