configure_dotfiles: yes
configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/enlewof/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/code/dotfiles
dotfiles_files:
  - .aliases
  - .bash_profile
  - .bashrc
  - .vimrc

homebrew_installed_packages:
  - bash-completion
  - bash-git-prompt
  - gpg
  - pass
  - pre-commit

homebrew_cask_apps: []
