configure_dotfiles: true
configure_sudoers: false
configure_terminal: false
configure_osx: false
configure_dock: true

dockitems_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - "System Preferences"
  - Calendar
  - TV
  - Podcasts
  - Music
  - News

dockitems_persist:
  - name: Brave Browser
    path: "/Applications/Brave Browser.app"
    pos: 1
  - name: Bitwarden
    path: "/Applications/Bitwarden.app"
    pos: 2
  - name: massCode
    path: "/Applications/massCode.app"
    pos: 3
  - name: Spotify
    path: "/Applications/Spotify.app"
    pos: 4

dotfiles_repo: git@github.com:enlewof/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/code/dotfiles
dotfiles_files:
  - .gitconfig
  - .git-template/hooks/pre-commit

homebrew_installed_packages:
  - antidote
  - bat
  - chezmoi
  - fzf
  - mise
  - neovim
  - knqyf263/pet/pet
  - pipx
  - pre-commit
  - lemoony/tap/snipkit
  - wget
  - zoxide

homebrew_cask_apps:
  - bitwarden
  - brave-browser
  - discord
  - google-chrome
  - gramps
  - iterm2
  - kodi
  - masscode
  - moonlight
  - nordvpn
  - philips-hue-sync
  - signal
  - sonos
  - spotify
  - steam
  - teamviewer
  - the-unarchiver
  - vlc

#pip_packages:
#  - name: pynvim
#    executable: pip3

pipx_packages:
  - name: nsz
    executable: pipx
  - name: libray
    executable: pipx
